### ISSUE TITLE
Questions about training time?

### ISSUE THREAD

**Issue by xiaoli1996** [evelyn0414/OPERA#1]
Hi,

I am currently reading your wonderful papers about the OPERA. I wonder how long OPERA trains on a single A100  GPU with 80G?

Thanks.

**Comment by evelyn0414** [comment]
Hi,

Thank you for your kind enquiry. All of the OPERA models require less than one day of training. The number of hours depends on the model architecture, with the OPERA-CE model needing only a few hours.

Best,
Evelyn
