### ISSUE TITLE
Conda Create Env Error

### ISSUE THREAD

**Issue by ERICXUCHI** [evelyn0414/OPERA#2]
Hi there,

I tried to test your code on my windows laptop, and there are lots of errors during "conda create" with your yml file.

Could you please test on your laptop or a new server, and upgrade the environment.yml? Because you included many your personal laptop info in this yml and perhaps there may be some problems.

Look forward to your reply, thanks for your effort!

**Comment by XTxiatong** [comment]
To run PyTorch code on Windows, we suggest you install Anaconda. You can follow the official instructions https://www.anaconda.com/download/success. Then, you can create an environment using the provided commands as introduced here https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html.   Running our scripts in Anaconda powershell prompt is the same as in linux.

**Comment by ERICXUCHI** [comment]
Yeah, I have tried these methods, but it seems that some dependencies are not suitable for windows. I don't know what's wrong. I have replaced my machine to linux and it works. BTW, I generated a more clean and complete environment.yml. I pull the request if it's ok.

**Comment by evelyn0414** [comment]
Hi,

Thanks for your interest and suggestion. We have updated the `environment.yml` file to reflect the current versions that OPERA uses.
